services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    env_file:
      - .env
    depends_on:
      - minio

  minio:
    image: minio/minio:latest
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    entrypoint:
      [
        "/bin/sh",
        "-c",
        "mkdir -p /data/flower && minio server /data --console-address ':9001'",
      ]
