services:
  minio:
    image: minio/minio:latest
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    entrypoint:
      [
        "/bin/sh",
        "-c",
        "mkdir -p /data/uploads && minio server /data --console-address ':9001'",
      ]