allowBuilds:
  '@parcel/watcher': true
  '@prisma/client': true
  better-sqlite3: true
  esbuild: true
  sharp: true
  unrs-resolver: true
  vue-demi: true
  workerd: true
onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@tailwindcss/oxide'
  - better-sqlite3
  - es5-ext
  - esbuild
  - sharp
  - unrs-resolver
  - vue-demi
  - workerd